docs: update migration message
OfficeDev/TeamsFx pull request #2530
Opened 2021-10-08 07:46 UTC by wenytang-ms

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/11209305

1. since ARM and Multi-Env feature enabled, toolkit need to migration project, otherwise, the project can not develop and use in the future.
2. during migration, .fx folder structure will changed, and create new ARM templates, Other unchanged.
3. it's better to backup the .fx folder, since migration is irreversible. For the backup method, consider using git.
4. once user click cancel, toolkit will continue to ask for migration when trigger teamsfx command. Unless  downgrade the toolkit or disable feature flags.

Message changes as

**We have detected that your toolkit supports ARM and Multi-Env features. In order to support the development and use of the project in the future, We will migrate your project. Migration will change the folder structure of the .fx, please backup this folder before migration, and we will create ARM templates for new version.**

2021-10-11 17:54 UTC, timngmsft commented
I don't think we have to tell people why their project will be migrated. This is a newer version of the toolkit; so we should migrate people along. @pierceboggan thoughts? This would be my proposal:

Teams Toolkit will migrate your project to support the latest features in Teams Toolkit 2.7.2. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back to Teams Toolkit 2.7.1.

(can you check that the version tags are correct?)

2021-10-12 01:51 UTC, wenytang-ms commented
> I don't think we have to tell people why their project will be migrated. This is a newer version of the toolkit; so we should migrate people along. @pierceboggan thoughts? This would be my proposal:
> 
> Teams Toolkit will migrate your project to support the latest features in Teams Toolkit 2.7.2. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back to Teams Toolkit 2.7.1.
> 
> (can you check that the version tags are correct?)

Thank you @timngmsft for your feedback. the message has updated, and the version start 2.7.0 will migration the project

**We will migrate your project to support the latest features in Teams Toolkit. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back to Teams Toolkit version below 2.7.0**

2021-10-12 02:02 UTC, adashen commented
> > I don't think we have to tell people why their project will be migrated. This is a newer version of the toolkit; so we should migrate people along. @pierceboggan thoughts? This would be my proposal:
> > Teams Toolkit will migrate your project to support the latest features in Teams Toolkit 2.7.2. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back to Teams Toolkit 2.7.1.
> > (can you check that the version tags are correct?)
> 
> Thank you @timngmsft for your feedback. the message has updated, and the version start 2.7.0 will migration the project
> 
> **We will migrate your project to support the latest features in Teams Toolkit. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back to Teams Toolkit version below 2.7.0**

The feature is still in "Insider" review.  Shall we call it out? Since actually turn off feature flag, there is no upgrade needed.

2021-10-12 03:38 UTC, wenytang-ms commented
message updated

**Teams Toolkit will migrate your project to support the latest features in Teams Toolkit. This process will change the contents of the '.fx' folder. Backup this folder or put your project in source control if you want to revert your project back below Teams Toolkit 2.7.0.**

2021-10-12 04:02 UTC, timngmsft requested changes

2021-10-12 04:02 UTC, timngmsft commented on packages/fx-core/resource/strings.json
> +    "MigrationToArmAndMultiEnvMessage": "Teams Toolkit will migrate your project to support the latest features in Teams Toolkit. This process will change the contents of the '.fx' folder. Backup thi
Just one more change - "Teams Toolkit will migrate your project to support the latest features. This process ..."

2021-10-12 04:28 UTC, timngmsft approved these changes

2021-10-12 04:33 UTC, merged