docs: update changelog and whatsnew
OfficeDev/TeamsFx pull request #6358
Opened 2022-10-13 09:17 UTC by MuyangAmigo

ms-teams-vscode-extension	v4.1.0-rc.1

CLI BREAKING CHANGE:
  

Extension-toolkit BREAKING CHANGE:
 

CLI feat commits:
  

Extension-toolkit feat commits:

2022-10-13 14:31 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +Incremental version for Teams Toolkit with new features and several enhancements.
This line can be removed.

2022-10-14 01:22 UTC, therealjohn requested changes
What's the purpose of having a CHANGELOG and WHATISNEW with the same content?

2022-10-14 01:22 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- New scenario-based Teams app template `Workflow bot` that enables you to create workflow style Teams application to facilitate users progress through multiple Adaptive Cards via buttons and inputs.
Use the new Workflow bot template to create sequential workflows where Adaptive Cards can be returned in response to user input. Learn more about this new template in the [documentation](https://aka.ms/teamsfx-card-action-response).

2022-10-14 01:22 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- Debugging process is now transparently defined in `.vscode/tasks.json` and accepts parameters and arguments to enable customization and provide more granular control over debugging processes. Check
Configure each step of the debugging experience in Teams Toolkit by customizing the `.vscode/tasks.json` file, which now [surfaces parameters for finer-tuned control](https://aka.ms/teamsfx-debug-tasks).

2022-10-14 01:22 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- Simplified single sign-on for Message Extension and Command bot via `Add sso` command and TeamsFx SDK that helps you leverage logged-in Teams user token when accessing Microsoft Graph from your Tea
Use the new **Add SSO** command for a simple way to [configure single sign-on for Message extension and Command bot projects](https://aka.ms/teamsfx-add-sso).

2022-10-14 01:22 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- SharePoint developers can now easily combine relevant web parts in a single personal Teams app as a [multi-tab Teams app](https://learn.microsoft.com/sharepoint/dev/spfx/build-for-teams-me-experien
SPFx developers can now combine web parts as a [multi-Tab Teams app](https://learn.microsoft.com/sharepoint/dev/spfx/build-for-teams-me-experience#build-a-multi-tab-personal-teams-app) using the **Add Feature** menu.

2022-10-14 01:22 UTC, therealjohn commented on packages/vscode-extension/WHATISNEW.md
> +## 4.1.0 - Oct 17, 2022
Same edits as above.

2022-10-14 05:44 UTC, merged

2022-10-14 07:24 UTC, MuyangAmigo commented
> What's the purpose of having a CHANGELOG and WHATISNEW with the same content?

@zyxiaoyuer Yu do you have context of this?