chore(vsc): align writing styles
OfficeDev/TeamsFx pull request #7785
Opened 2023-02-15 05:20 UTC by tecton

1. Capitalize strings.
2. Remove unused strings.

Related task: https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17061309

2023-02-15 06:20 UTC, HuihuiWu-Microsoft approved these changes

2023-02-15 10:22 UTC, sffamily requested changes

2023-02-15 10:22 UTC, sffamily commented on packages/vscode-extension/package.nls.json
> +    "teamstoolkit.guides.cardActionResponse.label": "Initiate Qequential Workflows in Teams",
Qequential -> Sequential

2023-02-16 06:45 UTC, tecton commented on packages/vscode-extension/package.nls.json
> +    "teamstoolkit.guides.cardActionResponse.label": "Initiate Qequential Workflows in Teams",
Thanks! Fixed now.

2023-02-16 07:02 UTC, sffamily approved these changes

2023-02-16 08:28 UTC, HuihuiWu-Microsoft approved these changes

2023-02-16 08:46 UTC, merged