chore(core): refine error strings to link to output channel
OfficeDev/TeamsFx pull request #7794
Opened 2023-02-15 12:23 UTC by jayzhang

2023-02-16 00:08 UTC, timngmsft requested changes

2023-02-16 00:08 UTC, timngmsft commented on packages/fx-core/resource/package.nls.json
> +  "core.deployArmTemplates.DeploymentFailedNotification": "resource deployments (%s) for your project failed. Please refer to [output channel](command:fx-extension.showOutputChannel) for more error d
Also remove "please".

2023-02-21 14:10 UTC, therealjohn approved these changes

2023-02-22 03:31 UTC, timngmsft approved these changes

2023-02-22 03:33 UTC, merged