chore: sync version can't read package.json.tpl file
OfficeDev/TeamsFx pull request #8292
Opened 2023-04-06 09:18 UTC by hund030

2023-04-06 09:20 UTC, yukun-dong approved these changes

2023-04-06 13:33 UTC, wenytang-ms commented
https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/17866310

2023-04-06 13:40 UTC, wenytang-ms requested changes
merge this pr to prerelease branch

2023-04-07 01:03 UTC, wenytang-ms approved these changes

2023-04-07 01:19 UTC, merged