docs: changelog and whatsnew for 0515 release
OfficeDev/TeamsFx pull request #8614
Opened 2023-05-05 10:33 UTC by MuyangAmigo

2023-05-05 18:01 UTC, therealjohn requested changes

2023-05-05 18:01 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- `Set signature using Outlook add-in`: An Outlook add-in that helps user to set their email signature.
"An Outlook add-in that demonstrates how to set an email signature.

2023-05-05 18:01 UTC, therealjohn commented on packages/vscode-extension/WHATISNEW.md
> +## 5.0.0 - May 15, 2023
Same edits that I suggested above apply to this file.

2023-05-06 09:04 UTC, MuyangAmigo commented
@therealjohn Thanks for the comments, I have updated all of them, please take another look.

2023-05-08 16:24 UTC, therealjohn approved these changes

2023-05-09 04:05 UTC, merged