feat(github): add create-milestone action
OfficeDev/TeamsFx pull request #8949
Opened 2023-06-07 02:54 UTC by xzf0587

2023-06-07 04:17 UTC, xzf0587 commented
run action: https://github.com/OfficeDev/TeamsFx/actions/runs/5195920654

2023-06-07 08:55 UTC, wenytang-ms commented on .github/workflows/create-milestone.yml
> +        uses: ./action-base/create-milestone
the path exist?

2023-06-08 02:02 UTC, wenytang-ms commented on .github/workflows/create-milestone.yml
> +        uses: ./action-base/create-milestone
but I don't find the create-milestone folder in the repo?

2023-06-08 02:03 UTC, wenytang-ms approved these changes

2023-06-08 02:04 UTC, wenytang-ms commented on .github/workflows/create-milestone.yml
> +        run: cp -r .github/actions/create-milestone ./action-base/create-milestone
before copy the repo's file, should this action checkout this TeamsFx first?

2023-06-08 02:05 UTC, wenytang-ms requested changes
should checkout current repo before cp action

2023-06-08 02:06 UTC, wenytang-ms approved these changes

2023-06-11 14:43 UTC, merged