feat: support additionalMetadata and sampleTag
OfficeDev/TeamsFx pull request #9533
Opened 2023-08-07 08:23 UTC by 1yefuwang1

https://msazure.visualstudio.com/Microsoft%20Teams%20Extensibility/_workitems/edit/24705240

2023-08-07 08:50 UTC, wenytang-ms approved these changes

2023-08-08 03:08 UTC, MuyangAmigo requested changes

2023-08-08 03:08 UTC, MuyangAmigo commented on packages/fx-core/resource/yaml-schema/v1.2/yaml.schema.json
> +      "additionalProperties": true,
Maybe just say `Metadata property, used by Teams Toolkit only`?

2023-08-08 03:08 UTC, MuyangAmigo commented on packages/fx-core/resource/yaml-schema/v1.2/yaml.schema.json
> +        }
`A tag for the sample app used to track telemetry events sent by Teams Toolkit associated with that sample. Pattern: <sample-repo>:<sample-name>`

2023-08-08 07:06 UTC, XiaofuHuang approved these changes

2023-08-08 07:07 UTC, HuihuiWu-Microsoft approved these changes

2023-08-08 07:08 UTC, SLdragon approved these changes

2023-08-08 07:09 UTC, xzf0587 approved these changes

2023-08-08 10:30 UTC, MuyangAmigo approved these changes

2023-08-08 10:46 UTC, jayzhang approved these changes

2023-08-09 04:22 UTC, sffamily approved these changes

2023-08-09 04:22 UTC, 1yefuwang1 commented on packages/fx-core/resource/package.nls.json
> +  "error.yaml.InvalidYamlSchemaErrorWithReason": "Unable to parse yaml file: %s. Reason: %s Please review the yaml file or upgrade to latest Teams Toolkit.",
I'll fix it in another PR.

2023-08-09 04:22 UTC, merged