docs: changelog for 0919 stable release
OfficeDev/TeamsFx pull request #9951
Opened 2023-09-14 09:38 UTC by MuyangAmigo

2023-09-14 09:51 UTC, kuojianlu submitted a review, later dismissed

2023-09-15 13:10 UTC, therealjohn requested changes

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +This minor version update of Teams Toolkit addresses your requests with new features and bug fixes, including import exiting SharePoint Framework solution, new app tempaltes for Link Unfurling and AI
"This minor version update of Teams Toolkit includes new features and bug fixes based on your feedback. The new features include the ability to import an existing SharePoint Framework solution, new project templates for Link Unfurling and AI Chat Bot, and more. We previously shared these incremental changes in the prerelease version and through a series of blog posts:"

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- A new link unfurling app template to help you get started with displaying rich content from links in Teams messages and Outlook emails.
"A new link unfurling project template to help you get started with displaying rich content from links in Teams messages and Outlook emails."

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- A new app template `AI Chat Bot` to help you get started with building a GPT-like chat bot with AI capabilities using `Teams AI Library`.
"A new AI Chat Bot project template to help you get started with building a GPT-like chat bot with AI capabilities using the [Teams AI Library](https://github.com/microsoft/teams-ai)."

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- Onboarded a new sample `One Productivity Hub using Graph Toolkit with SPFx` that shows you how to build a tab for viewing your calendar events, to-do tasks and files by using Microsoft Graph Toolki
"The Sample Gallery has a new sample, One Productivity Hub using Graph Toolkit with SPFx, that shows you how to build a Tab for viewing your calendar events, to-do tasks, and files using Microsoft Graph Toolkit components and a SharePoint provider."

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- Added CodeLens to the `teamsapp.yml` file to help you run life-cycle commands easily after editing the file.
"Run life-cycle commands like Provision, Deploy, and Publish using new CodeLens hints added in-line to `teamsapp.yml` and `teamsapp.local.yml` when editing the file."

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +- Fixed an issue where the `Preview` tag for the `AI Chat Bot` app template was not included in previous version. ([#9901](https://github.com/OfficeDev/TeamsFx/pull/9901))
Prefer "project template" over "app template"

2023-09-15 13:10 UTC, therealjohn commented on packages/vscode-extension/CHANGELOG.md
> +More details on other enhancements, bug fixes and updates on Teams Toolkit CLI and TeamsFx SDK can be found from the blogs.
Remove this line.

2023-09-18 04:49 UTC, eriolchan approved these changes

2023-09-18 04:49 UTC, merged